"""add status to organization invitation

Revision ID: 29b5fe10a466
Revises: 2b120773bf5c
Create Date: 2025-12-15 02:03:41.411188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29b5fe10a466'
down_revision: Union[str, Sequence[str], None] = '2b120773bf5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_invitation', sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', name='status_enum'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization_invitation', 'status')
    # ### end Alembic commands ###
