"""edit file info4

Revision ID: 865f774f10b3
Revises: c2954787fe46
Create Date: 2026-01-15 20:35:52.777571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '865f774f10b3'
down_revision: Union[str, Sequence[str], None] = 'c2954787fe46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('receipt_receipt_image_id_fkey'), 'receipt', type_='foreignkey')
    op.drop_column('receipt', 'receipt_image_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipt', sa.Column('receipt_image_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('receipt_receipt_image_id_fkey'), 'receipt', 'file_info', ['receipt_image_id'], ['id'])
    # ### end Alembic commands ###
