"""connect file info to organization

Revision ID: 889d68022a6b
Revises: 180b62c2264f
Create Date: 2026-01-13 18:19:46.352334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '889d68022a6b'
down_revision: Union[str, Sequence[str], None] = '180b62c2264f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_info', sa.Column('organization_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'file_info', 'organization', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'file_info', type_='foreignkey')
    op.drop_column('file_info', 'organization_id')
    # ### end Alembic commands ###
