"""edit file info3

Revision ID: c2954787fe46
Revises: 759fce4bd0d0
Create Date: 2026-01-15 20:30:08.031263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2954787fe46'
down_revision: Union[str, Sequence[str], None] = '759fce4bd0d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file_info', 'receipt_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'file_info', 'receipt', ['receipt_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'file_info', type_='foreignkey')
    op.alter_column('file_info', 'receipt_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
