"""edit file info

Revision ID: c85195064f6d
Revises: 889d68022a6b
Create Date: 2026-01-15 03:00:59.496884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c85195064f6d'
down_revision: Union[str, Sequence[str], None] = '889d68022a6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_info', sa.Column('receipt_id', sa.Integer(), nullable=False))
    op.drop_column('file_info', 'original_file_name')
    op.drop_column('file_info', 'file_size')
    op.drop_column('file_info', 'file_url')
    op.drop_column('file_info', 'content_type')
    op.add_column('receipt', sa.Column('receipt_image_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'receipt', 'file_info', ['receipt_image_id'], ['id'])
    op.drop_column('receipt', 'receipt_image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipt', sa.Column('receipt_image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'receipt', type_='foreignkey')
    op.drop_column('receipt', 'receipt_image_id')
    op.add_column('file_info', sa.Column('content_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('file_info', sa.Column('file_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('file_info', sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('file_info', sa.Column('original_file_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('file_info', 'receipt_id')
    # ### end Alembic commands ###
